theme: jekyll-theme-minimal
logo: /image/gitgithub.png
title: "Git project"
description: "This presentation is a summary of the most used git commands".
show_downloads: true
url:  " https://mohamedalybouri.github.io/"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

language: ruby
cache: bundler
rvm: 2.6

install: script/bootstrap
script: script/cibuild