title: Git presentation
name : Mohamed Ali Bouri
description: This presentation is a summary of the most used git commands
show_downloads: false
google_analytics:
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed

include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
#sass
sass:
  style: compressed

.site-title::before {
content: url("https://avatars.githubusercontent.com/u/89728610?v=4");
display: inline-block;
position: relative;
width: 32px;
top: 32px;