title: Git presentation
logo: /image/gitgithub - Copie.png
description: This presentation is a summary of the most used git commands
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal