title: Git presentation
name : Mohamed Ali Bouri
description: This presentation is a summary of the most used git commands
show_downloads: false
google_analytics:
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed

include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
#sass
sass:
  style: compressed