theme: jekyll-theme-minimal
logo: /image/gitgithub.png
title: Git project
description: This presentation is a summary of the most used git commands.
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
