title: Git presentation
logo: /image/gitgithub - Copie.png
description: This presentation is a summary of the most used git commands
show_downloads: false
google_analytics:
markdown: kramdown
highlighter: rouge
theme: minimal
gems:
  - jekyll-feed

include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
#sass
sass:
  style: compressed